export const signatories = [
    "21–87",
    "216 Signs",
    "31% Wool",
    "400",
    "A–Side.",
    "Aalia Ahamed",
    "Abbie Williams",
    "abc",
    "ACRE – A Creative Endeavour Ltd",
    "Active Matter",
    "ACX",
    "Adele Kelly",
    "AdesignStorie",
    "Advocate Design Agency",
    "Aetha Design",
    "Aileron Design Ltd",
    "Alan Pitchforth",
    "Alex Kimber Design",
    "Alexander Miller",
    "Alexandra Lunn Studio",
    "Alexandra Lunn Studio",
    "Alexie Sommer",
    "Alexis Bardini",
    "Ali Adair",
    "Andrew Carr",
    "ANdy Parker",
    "Andy Thornton",
    "Anja Klüver",
    "Annabelle Vuille",
    "Apfel",
    "Applied Works",
    "Archetype Accessories",
    "Arif Yusop",
    "Arrival",
    "Avery & Brown",
    "BA (Hons) Design for Sustainable Futures at Arts University Bournemouth",
    "BA Graphic Design at Kingston School of Art",
    "Badfish Labs",
    "Baines Design LTD",
    "Barbara Chandler",
    "Barry Bloye",
    "Batch.Works",
    "Baxter & Bailey",
    "Be The Future",
    "Beco",
    "Beehive Green",
    "Ben Clarke",
    "Ben Jessop",
    "Bencium Limited",
    "Benedict Povey",
    "Beta Design Office",
    "BIB Design",
    "big fish",
    "Big Motive",
    "Bill Searle",
    "Biomimicry Innovation Lab",
  "Bliss",
  "Blunt Crayon",
  "Bold Studio",
  "Boyle & Perks",
  "Brand Narrative at Pentagram",
  "Bravand",
  "Breezign",
  "Bright Signals Design at Bright Signals Ltd.",
  "Broadley Creative Ltd",
  "Bronwen Rees",
  "Buff Motion",
  "Butterfly",
  "BuyDesign",
  "Carter Studio",
  "Célibataire",
  "Charli Blighton",
  "Charli Peake",
  "Charlotte Eagle",
  "Charlotte Evans",
  "Cherry Anderson Freelance Design",
  "Chloe Poulter",
  "Claire O’Neill",
  "Claire Potter Design",
  "Clara Greo",
  "Clare Lewis",
  "Claudiu",
  "Clever Ghost",
  "Climate Labs",
  "Clive Russell",
  "COHDA Design",
  "Companion Studio",
  "Conscious Hospitality Ltd",
  "Conscious Sourcing",
  "Contour",
  "Creative at Delarki",
  "Creative Concern",
  "creative conscience",
  "Creative Joy",
  "Creative Joy",
  "Creative Wilderness LTD",
  "Curious Agency",
  "Curious Agency",
  "Curious Brand",
  "CyDen Ltd",
  "D Squared Product Development Ltd",
  "Daedalus",
  "Daryl Wilkinson",
  "Dave Cartledge",
  "Dave Cuvelot",
  "David Fairbrother",
  "David Sudlow Designers",
  "DEFY Brands",
  "Design Activists for Regenerative Futures",
  "Design Burger",
  "Design by Country Ltd",
  "Design by Mondial",
  "Design Council",
  "Design For Good Club",
  "Design for Joy",
  "Design Nature CIC",
  "Design Science",
  "Design Truth",
  "DesignWright",
  "DH Design Studios Ltd",
  "Dids Macdonald",
  "Dionne Griffith",
  "Diploma in Professional Studies at London College of Communication",
  "DISOMT",
  "Dominik Bini",
  "Dr Emma Powell",
  "Dr Karl Jeffries",
  "Drew Kendrick",
  "Driftime® Media",
  "Dylan Wiener",
  "ecologicstudio",
  "Edmuuund",
  "Electro Strategy",
  "Element Studio",
  "Eleven",
  "elise",
  "Ella Porter",
  "Elle Nelson Design",
  "Ellie Burroughs",
  "Emily Gorham",
  "EMMA BRITTAIN",
  "Emma Summerscales",
  "emmabakerstudio",
  "Eniola Ogunsola",
  "Ensemble",
  "Enviral",
  "Etch",
  "Ettive Design",
  "Europa",
  "Eva Koehle",
  "Everything",
  "Everywhere Design",
  "Exeter Waste",
  "F VENZANO",
  "Fairground Studio",
  "Farrah & Pearce Ltd",
  "FearNaught",
  "Fernanda Rizzo",
  "Ferrgood Studio",
  "Few and Far",
  "Fighting Talk Communications",
  "Fiona Watkins Design Limited",
  "Fixperts at Forth",
  "Foundation",
  "Founded Design Ltd",
  "Fourfeet Design",
  "Francesca Cook Design Ltd",
  "Francis Rowland",
  "Frankie Thelwell",
  "FranklinTill",
  "Future Island-Island at Ulster University-led consortium",
  "Future Selves",
  "Futurice Ltd",
  "Fynn",
  "G R Moore Limited",
  "G3 Creative",
  "Gareth Neal Ltd",
  "Gareth Wild",
  "Garlic Agency",
  "Genevieve Bennett Ltd",
  "Genuinely Conscious",
  "George Charnley",
  "George Rowland",
  "GET LOST",
  "Gianfranco Fagotto",
  "Gitta Gschwendtner Ltd",
  "Giulia Villa",
  "Glen Cutwerk",
  "Glimpse",
  "Good Design Works",
  "Good Stuff Creative",
  "Good Will Studios",
  "Goodtale",
  "Goodwin Hartshorn",
  "Graduate Studies at College for Creative Studies",
  "Graft Creative",
  "Green Mat Workshop",
  "Green Orbit Digital",
  "Green Rooms landscapes & gardens",
  "GreenHeights",
  "H&A",
  "Hamish Duncan",
  "Hamish Makgill",
  "Han Li",
  "Hannah Pinnock",
  "Harriet Beesley",
  "Harrison Brands Ltd",
  "Haughton Design",
  "Helen Simmons",
  "Hey Low",
  "Hippo Digital",
  "Hive IT",
  "Hiyield",
  "Holmes Studio",
  "honours",
  "HOUSE OF HACKNEY",
  "Hundred Studio",
  "ICE",
  "ilka design limited",
  "Imagination Factory",
  "Inspirwood",
  "INTRA DRIVE LTD",
  "Irina Teti",
  "Isabella",
  "Jackie Malcolm",
  "Jake Owen",
  "James Kindred",
  "James Tooze",
  "Jamie Pinkham",
  "jan lewis creative",
  "Jane Penty",
  "Jason Bruges Studio",
  "Jason Mesut",
  "Jemima Duncalf",
  "Jess Baxter",
  "Jess Francis",
  "JK Creative Company",
  "Jo Mansfield",
  "Joanna boehnert",
  "John Gilbert",
  "Joseph Folkes",
  "Josh Elgood",
  "Joshua Tunstill",
  "Jude Pullen",
  "Juice by Design",
  "Justine Wyness",
  "Kaelum van der Berg",
  "Kai Davis",
  "Kaleido Grafik",
  "Kaleido Grafik",
  "Kanika Kalra",
  "Karishma Kusurkar",
  "Kathryn Summers",
  "Kavya Narayanan",
  "Kenny Heard",
  "Kenwood Design Office (KDO) at Kenwood Limited",
  "Kim Trow",
  "Kinneir Dufort",
  "Kirsten Gord",
  "KLUVERWORKS",
  "Kyle Soo",
  "Kyle Stuart Florent Taylor",
  "Laura Santamaria",
  "Laure Rees-Smith",
  "Lawrence Zeegen",
  "Layerd.Studio",
  "Leap Design",
  "Lewis Plummer",
  "Liam O'Brien",
  "Lil Creative Studio",
  "Limber Brands",
  "Liquid Studio Ltd",
  "Lobo Creative",
  "LowCarbon",
  "Lucy Carruthers",
  "Lucy Watkins",
  "Luigi Gisolfi",
  "Lyon & Lyon",
  "MA Sustainable Design at University of Brighton",
  "Made for the World",
  "madeby.studio",
  "Magnus Long Studio",
  "Mainlyphotography Studio",
  "Mani I",
  "Mantra",
  "Mar Mar Co. Studio",
  "March Studio Ltd",
  "Maria Elina",
  "Marion Ratie",
  "Mark Hicks",
  "Marta De Prisco",
  "MARTA ROSSATO INTERIORS",
  "Martin Hopkins",
  "Martin Price",
  "Martin Wright",
  "Mat Denney",
  "Materialise Interiors",
  "Materials Council",
  "MaterialsInformation Ltd",
  "Matt Hollands",
  "Matteo Menapace",
  "Matter + Perspective",
  "Matthew Kilcullen",
  "Max Fraser",
  "Maya Designer",
  "Mia Allers",
  "Micha Nicheva",
  "Michael James",
  "Michael Love Design",
  "Michael Norrington",
  "Michael Rawling",
  "Midnight",
  "Minna Takala",
  "Mireia Allende",
  "Mitre and Mondays",
  "Mocean",
  "ModularPlastik",
  "Monica Oliveira",
  "MONOMOTIF",
  "Morrama",
  "Muddy Machines",
  "Muta Futures Studio",
  "Nagonic Design Ltd",
  "Naked Ideas",
  "Nat Hunter",
  "Natalia Benusiglio Stern",
  "Natalie Perkins",
  "Nefeli Pavlou Musio",
  "Neol.co",
  "Never Not Ready",
  "Nicola Holden Designs",
  "Nils Aksnes",
  "noel douglas",
  "Norah Joshi (Lewis)",
  "Noughts & Ones",
  "NU Creative Ltd",
  "NU Design Spaces",
  "Nurture",
  "Objective Studio",
  "observerly",
  "Octo Design Ltd",
  "OGRE Studio",
  "Ohana Studio Ltd",
  "Ok deploy",
  "Ole Makkesen Designlab",
  "Olive Kennington",
  "Oliver Lloyd",
  "Olivia Harris",
  "OneKind Creative",
  "Optimist Works",
  "Oracle Design",
  "Orangery",
  "ORCA",
  "Osch",
  "Other Today",
  "OURI Labs",
  "OXygen",
  "Papaya–Studio",
  "Papillon Bleu",
  "Paul Bailey",
  "Paul Gibson Design",
  "Pearson Lloyd",
  "People Planet Product",
  "Phase Two",
  "Pixel Fridge LTD",
  "Pollenize CIC",
  "Polytechnic",
  "Poonum Chauhan",
  "Pretty Clever",
  "Product Design at University of Brighton",
  "Product Design at University of Sussex",
  "Product for Net Zero",
  "Purple Banana",
  "QED web design",
  "Rahul Anand",
  "Realise",
  "Rebekah Di Palma",
  "ReShaped Landscape",
  "Rhapsody Media",
  "Rhombus Studio",
  "Ria Hawthorn",
  "Richa Gandhi",
  "Robin Wong",
  "Roddy Clarke",
  "Rory Cowan",
  "Roundwave",
  "Ruddocks",
  "Ruth Wassermann Ltd",
  "Sabotage",
  "Sam Judge",
  "Samuel Marchant",
  "Sandrine Herbert-Razafinjato",
  "sassd",
  "School of Good Services",
  "Selesti",
  "Selina Rose",
  "Set Studio",
  "Seth Campbell",
  "Sheffield Creative Industries Institute at Sheffield Hallam University",
  "Simone Cucchi",
  "Snook",
  "Social Change",
  "Sophie Mockridge",
  "Sophie Reynolds",
  "Sophie Thomas",
  "Spark & Bell",
  "Special Projects",
  "Spotless",
  "Sruti Gidugu",
  "sssfsf",
  "Standfirst",
  "Stefan Bassing",
  "Still&Nimble",
  "Storo",
  "Straight Forward Design",
  "Stuart Gough",
  "Studio Breuil",
  "Studio Casey Joy",
  "Studio Elk",
  "Studio Elma",
  "Studio Every",
  "Studio Gallant",
  "Studio Joana",
  "Studio KICO",
  "Studio Mothership",
  "Studio Olivers",
  "Studio Ology",
  "Studio Output",
  "Studio Overberg",
  "Studio Simple",
  "Studio Technical Nature",
  "Studio Tom Metcalfe",
  "Studio Wood",
  "Submarine",
  "Substance",
  "Superfried",
  "Susanna Edwards",
  "Susannah Kabuiku",
  "Sustainable Ventures Design",
  "T&B Design",
  "Tacit-Tacit",
  "Takram",
  "TAMART",
  "Tempest",
  "TEN by Anatomy HCD Limited",
  "Teresa Ferreira Studio",
  "Terrarium",
  "The Art and Design Consultancy",
  "The Blooming Platypus",
  "The Creative Bloc",
  "The Digital Creative London Ltd.",
  "The Discourse",
  "THE FOURTH SOLUTION",
  "The Landscape",
  "The Looking Glass",
  "The Manufacturing Technology Centre",
  "Theo Dormer",
  "Think/Do",
  "Thinkpublic",
  "Thom Baker Consultancy",
  "Thomas Baraldi Cassaro",
  "Thomas Wylam",
  "thomas.matthews",
  "Thoughtcraft",
  "Tijana Tasich",
  "Tim Frenneaux & Co",
  "Tina Bernstein",
  "TLC",
  "Tokyo Calm",
  "Tokyo Calm",
  "Tom Greenwood",
  "Tomas Gecim",
  "Tommy Papaioannou",
  "Tria Design",
  "Tristan Palmer Studio",
  "Two",
  "Two Degrees Studio",
  "Tŷ Syml",
  "Unboxed",
  "Unfound Studio",
  "United by Design",
  "UnlikelyGenius",
  "URGE Collective",
  "Vashti Waite",
  "Vestre Ltd",
  "Vicky Lofthouse",
  "Virgile Janssen",
  "Visual Print and Design",
  "VIVID NINE",
  "Vovi",
  "Vox Aeris",
  "Vu Online",
  "We Are Service Works Ltd",
  "We Are Systematic",
  "We Made This Ltd",
  "We Mean This",
  "WEAMO",
  "West9 Design",
  "White Weft Limited",
  "Wholegrain Digital",
  "WizzDev",
  "Working with Joe Ltd",
  "Works in Public Ltd",
  "www.archetypeaccessories.com",
  "xforwhy",
  "XTATX Studio",
  "Yarn Creative",
  "yesim tuzun",
  "Yoke design",
  "Zebra Growth Limited",
  "Zoe Bather",
  "ZOOZLY",
  "this also",
];


export const globalSupporters = [
  {
    country: "Argentina",
    supporters: ["Celina Hilbert"]
  },
  {
    country: "Australia",
    supporters: [
      "Alena Smith Interior Design",
      "Andrew Sloan",
      "Andrew Vaughan",
      "Andy Marks",
      "Arielle Bret",
      "Art Disrupt",
      "Austin Smidt",
      "AUTHENTIC DESIGN ALLIANCE (ADA)",
      "Ben Rennie",
      "BETTER FUTURE",
      "Bohdan Dorniak & Co Pty Ltd - PROSPECT, SA",
      "Brand & Communications at Edge Impact",
      "Breathe Architecture",
      "BWD Strategic",
      "Cameron Tonkinwise",
      "Carbon Creative",
      "Carolyn King",
      "Celine Waters",
      "Chris Speed",
      "Design by Nature",
      "Design Consigned",
      "Diadem",
      "Dr Michelle Douglas FRSA",
      "eco creative agency",
      "Ethos Digital Agency",
      "Finbar",
      "Founded by Design Pty Ltd",
      "Frost*",
      "Frost*",
      "Gabriella Wilson",
      "Genius Agency",
      "Geoff Isaac",
      "Glen Barry",
      "Glen Barry",
      "Gloria Quiroga",
      "Good 4 Business",
      "Good Design Australia",
      "Good Design Australia",
      "Goodness",
      "Goodsports",
      "Hammond Studio",
      "Harry Steer",
      "Heidi Romano",
      "Holonic",
      "Hortenzia",
      "James Hodgson Design",
      "Jas Soh",
      "Jeremy Yuille",
      "Jo Li Tay",
      "John Young",
      "Josh Riesel",
      "Karina Clarke",
      "Katapult Design",
      "Kirby C",
      "Koskela",
      "Leigh Phillips-Brown",
      "Leigh-Anne Hepburn",
      "Leyla Acaroglu",
      "Liane Rossler",
      "LPB Designs and Interiors",
      "Madeline Johnston",
      "Make Tomorrow™",
      "Marnie Hawson",
      "Martin Tomitsch",
      "MEK Studio",
      "Mirella Arapian",
      "Moffitt.Moffitt.",
      "Motherbird",
      "Nacara Studio",
      "Nila Rezaei",
      "Particle Design Studio",
      "Philip Ely PhD",
      "philo & co",
      "Planitree",
      "Reny Studio",
      "Reny®",
      "Ricardo Sosa",
      "RK Collective",
      "RMIT University",
      "Samuel Yu",
      "Seek & Design",
      "Snug House",
      "Society for Responsible Design Inc.",
      "Sponge",
      "Stephanie Mulder",
      "Steve Baty",
      "STUDIO PERISCOPE",
      "Studio Regina",
      "studiospillane",
      "Tanisha Maria Naik",
      "The Design Thinkers",
      "UNEND",
      "United Studio",
      "vert design",
      "Wendy Fountain",
      "X+O",
      "Ys",
      "Zero Co pty Ltd",
    ]
  },
  {
    country: "Austria",
    supporters: ["Luain"]
  },
  {
    country: "Bangladesh",
    supporters: ["Rifat Anik"]
  },
  {
    country: "Belgium",
    supporters: [
      "Air",
      "Blue Kameleon SRL",
      "Core Branding",
      "Futurewave",
      "HIER",
      "Orb",
    ]
  },
  {
    country: "Brazil",
    supporters: [
      "Adriana Tamashiro",
      "Agatha Martins",
      "Alexander Ângelo Guazzelli",
      "Alexandre de Oliveira Lot",
      "Amanda Lima Neves Scorsolini",
      "Ana Luísa Canto",
      "Ana Paula Batista",
      "Audrey Italo Melo",
      "BRQ Digital Solutions",
      "Bruna Cerasi",
      "Bruna Luiza Schwendler",
      "Bruna Mattos",
      "Brunna Moura",
      "BRUNO FREIRE PERRONE",
      "Cacto Publicidade",
      "Camila Calegari Marques",
      "Camila de Almeida Santos",
      "Camila Lozeckyi",
      "Carlos Filipe Alves Lima",
      "Carlos Ignacio Hernández Tellez",
      "Carol Hoffmann",
      "CECILIA PACHECO",
      "Chelles & Hayashi Design",
      "christian ullmann",
      "Claudia Mardegan",
      "Claudio Pelizari",
      "Danton Gravina",
      "Denilson Silva",
      "Denise Oliveira Martins",
      "Design Docol at Docol Sanitaryware",
      "Design Team at WIS Learn",
      "DI",
      "Diego Nunes",
      "Diogo Lucato",
      "DPO Saudável",
      "Echos",
      "Eduardo Maia",
      "Eliane Quadro",
      "Empathy Company",
      "Estúdio Atômico",
      "Estúdio Guto Requena",
      "Estudio Marte",
      "Fares Saba Jr",
      "Fernanda",
      "Fernanda Fidelis",
      "Fernanda Romera",
      "Fluyd",
      "Francisco Albuquerque",
      "GABRIEL ESTEVES DE OLIVEIRA LEITAO",
      "George Rutherford",
      "GIOVANA LORENA FAZIONI",
      "Green Mandarin",
      "Green Mandarin",
      "Greg Lopes",
      "IMK Arquitetura e Engenharia",
      "Jaakko Tammela",
      "Jenifer Rodrigues",
      "Juan Solís Gundín",
      "JULIA RESENDE",
      "Júlia Timponi",
      "JULIANA SIDSAMER",
      "Julianny aidel rafea",
      "Junior Magalhães",
      "KAREN TIE KAWAKAMI",
      "Karla Scherer",
      "Larissa Nunes",
      "Leo Eyer",
      "Leonardo Lins",
      "Lincoln Seragini",
      "Lincoln Shiguio",
      "Lincoln Shiguio",
      "Luciana Shirakawa",
      "LUIS FERNANDO OSCAR COSTA",
      "Maialu Ferlauto",
      "Marcelo F. Pereira Junior",
      "Marcelo Sales",
      "Marcon Zanin",
      "Marcos Vinícius Machado de Oliveira",
      "Maria de Fátima Gullino Frazão",
      "Maria Elisa Zaia",
      "Mariana Fonseca de Souza",
      "Mariana Pereira Weber",
      "Mateus Bull Furlan",
      "Mayra Sasso",
      "Nathalia Petta",
      "paaassos design studio",
      "Pamela Basilio",
      "Patricia Watson",
      "Paula Cristiani Takahashi",
      "Paulo Peres",
      "Paulo Santos",
      "Pedro Gomes",
      "Pedro Martins e Souza",
      "Pedro Naif",
      "Pedro Pazitto",
      "PPTzeiros",
      "Raissa Esther",
      "Raquel Lima",
      "RedBandana Branding and Design",
      "Rei Campos Inovação em Serviços",
      "Renan Benvenuti",
      "Renan Migliorini",
      "Renata matos",
      "Renato Winnig",
      "Robson Zumkeller",
      "Robson Zumkeller",
      "RODRIGO ANTONIO QUEIROZ COSTA",
      "Rodrigo Peixoto",
      "Sandra Ribeiro Cameira",
      "Simbïo Design",
      "Studio Allure",
      "tellus",
      "Thayane",
      "Thiago Barreto",
      "Thiago Vieira Marques",
      "Thoz",
      "tiago taveira",
      "Tudo é Acessibilidade",
      "UERJ",
      "Vagner Trevisan",
      "Vanessa Silva",
      "Victor Maluhy",
      "Victor Mascarenhas",
      "VIRGINIA CORNELSEN",
      "Visorama",
      "Wagner Lúcio",
      "weme"
    ]
  },
  {
    country: "Bulgaria",
    supporters: ["Ivelina Dimitrova"]
  },
  {
    country: "Canada",
    supporters: [
      "À Hauteur d'homme",
      "Ardeshir Amini",
      "Cense Ltd.",
      "Elane Bowden",
      "Fletcher Scott Studio Inc.",
      "Meghan Hellstern",
      "PITCH PR",
      "PITCH PR",
      "Project 42",
      "Ryan Mayer",
      "SUPERFORT Creative Agency"
    ]
  },
  {
    country: "China",
    supporters: [
      "Campaign Design",
      "Orange Creatives",
      "Platform88"
    ]
  },
  {
    country: "Colombia",
    supporters: [
      "Adelaida Gonzalez",
      "Andrea Gonzalez OSCAR"
    ]
  },
  {
    country: "Croatia",
    supporters: ["Entain"]
  },
  {
    country: "Guatemala",
    supporters: ["Fabrizio Constanza"]
  },
  {
    country: "India",
    supporters: [
      "A BLUNT STORY",
      "Aboa Hasa Foundation",
      "Dinu Prasanna Kennedy",
      "DxE Inc.",
      "LOCAL",
      "Minto Joy",
      "Sai Challa",
      "Shona Sinha",
      "Shreya Salian"
    ]
  },
  {
    country: "Argentina",
    supporters: ["Celina Hilbert"]
  },
  {
    country: "Australia",
    supporters: [
      "Alena Smith Interior Design",
      "Andrew Sloan",
      "Andrew Vaughan",
      "Andy Marks",
      "Arielle Bret",
      "Art Disrupt",
      "Austin Smidt",
      "AUTHENTIC DESIGN ALLIANCE (ADA)",
      "Ben Rennie",
      "BETTER FUTURE",
      "Bohdan Dorniak & Co Pty Ltd - PROSPECT, SA",
      "Brand & Communications at Edge Impact",
      "Breathe Architecture",
      "BWD Strategic",
      "Cameron Tonkinwise",
      "Carbon Creative",
      "Carolyn King",
      "Celine Waters",
      "Chris Speed",
      "Design by Nature",
      "Design Consigned",
      "Diadem",
      "Dr Michelle Douglas FRSA",
      "eco creative agency",
      "Ethos Digital Agency",
      "Finbar",
      "Founded by Design Pty Ltd",
      "Frost*",
      "Frost*",
      "Gabriella Wilson",
      "Genius Agency",
      "Geoff Isaac",
      "Glen Barry",
      "Glen Barry",
      "Gloria Quiroga",
      "Good 4 Business",
      "Good Design Australia",
      "Good Design Australia",
      "Goodness",
      "Goodsports",
      "Hammond Studio",
      "Harry Steer",
      "Heidi Romano",
      "Holonic",
      "Hortenzia",
      "James Hodgson Design",
      "Jas Soh",
      "Jeremy Yuille",
      "Jo Li Tay",
      "John Young",
      "Josh Riesel",
      "Karina Clarke",
      "Katapult Design",
      "Kirby C",
      "Koskela",
      "Leigh Phillips-Brown",
      "Leigh-Anne Hepburn",
      "Leyla Acaroglu",
      "Liane Rossler",
      "LPB Designs and Interiors",
      "Madeline Johnston",
      "Make Tomorrow™",
      "Marnie Hawson",
      "Martin Tomitsch",
      "MEK Studio",
      "Mirella Arapian",
      "Moffitt.Moffitt.",
      "Motherbird",
      "Nacara Studio",
      "Nila Rezaei",
      "Particle Design Studio",
      "Philip Ely PhD",
      "philo & co",
      "Planitree",
      "Reny Studio",
      "Reny®",
      "Ricardo Sosa",
      "RK Collective",
      "RMIT University",
      "Samuel Yu",
      "Seek & Design",
      "Snug House",
      "Society for Responsible Design Inc.",
      "Sponge",
      "Stephanie Mulder",
      "Steve Baty",
      "STUDIO PERISCOPE",
      "Studio Regina",
      "studiospillane",
      "Tanisha Maria Naik",
      "The Design Thinkers",
      "UNEND",
      "United Studio",
      "vert design",
      "Wendy Fountain",
      "X+O",
      "Ys",
      "Zero Co pty Ltd",
    ]
  },
  {
    country: "Austria",
    supporters: ["Luain"]
  },
  {
    country: "Bangladesh",
    supporters: ["Rifat Anik"]
  },
  {
    country: "Belgium",
    supporters: [
      "Air",
      "Blue Kameleon SRL",
      "Core Branding",
      "Futurewave",
      "HIER",
      "Orb",
    ]
  },
  {
    country: "Brazil",
    supporters: [
      "Adriana Tamashiro",
      "Agatha Martins",
      "Alexander Ângelo Guazzelli",
      "Alexandre de Oliveira Lot",
      "Amanda Lima Neves Scorsolini",
      "Ana Luísa Canto",
      "Ana Paula Batista",
      "Audrey Italo Melo",
      "BRQ Digital Solutions",
      "Bruna Cerasi",
      "Bruna Luiza Schwendler",
      "Bruna Mattos",
      "Brunna Moura",
      "BRUNO FREIRE PERRONE",
      "Cacto Publicidade",
      "Camila Calegari Marques",
      "Camila de Almeida Santos",
      "Camila Lozeckyi",
      "Carlos Filipe Alves Lima",
      "Carlos Ignacio Hernández Tellez",
      "Carol Hoffmann",
      "CECILIA PACHECO",
      "Chelles & Hayashi Design",
      "christian ullmann",
      "Claudia Mardegan",
      "Claudio Pelizari",
      "Danton Gravina",
      "Denilson Silva",
      "Denise Oliveira Martins",
      "Design Docol at Docol Sanitaryware",
      "Design Team at WIS Learn",
      "DI",
      "Diego Nunes",
      "Diogo Lucato",
      "DPO Saudável",
      "Echos",
      "Eduardo Maia",
      "Eliane Quadro",
      "Empathy Company",
      "Estúdio Atômico",
      "Estúdio Guto Requena",
      "Estudio Marte",
      "Fares Saba Jr",
      "Fernanda",
      "Fernanda Fidelis",
      "Fernanda Romera",
      "Fluyd",
      "Francisco Albuquerque",
      "GABRIEL ESTEVES DE OLIVEIRA LEITAO",
      "George Rutherford",
      "GIOVANA LORENA FAZIONI",
      "Green Mandarin",
      "Green Mandarin",
      "Greg Lopes",
      "IMK Arquitetura e Engenharia",
      "Jaakko Tammela",
      "Jenifer Rodrigues",
      "Juan Solís Gundín",
      "JULIA RESENDE",
      "Júlia Timponi",
      "JULIANA SIDSAMER",
      "Julianny aidel rafea",
      "Junior Magalhães",
      "KAREN TIE KAWAKAMI",
      "Karla Scherer",
      "Larissa Nunes",
      "Leo Eyer",
      "Leonardo Lins",
      "Lincoln Seragini",
      "Lincoln Shiguio",
      "Lincoln Shiguio",
      "Luciana Shirakawa",
      "LUIS FERNANDO OSCAR COSTA",
      "Maialu Ferlauto",
      "Marcelo F. Pereira Junior",
      "Marcelo Sales",
      "Marcon Zanin",
      "Marcos Vinícius Machado de Oliveira",
      "Maria de Fátima Gullino Frazão",
      "Maria Elisa Zaia",
      "Mariana Fonseca de Souza",
      "Mariana Pereira Weber",
      "Mateus Bull Furlan",
      "Mayra Sasso",
      "Nathalia Petta",
      "paaassos design studio",
      "Pamela Basilio",
      "Patricia Watson",
      "Paula Cristiani Takahashi",
      "Paulo Peres",
      "Paulo Santos",
      "Pedro Gomes",
      "Pedro Martins e Souza",
      "Pedro Naif",
      "Pedro Pazitto",
      "PPTzeiros",
      "Raissa Esther",
      "Raquel Lima",
      "RedBandana Branding and Design",
      "Rei Campos Inovação em Serviços",
      "Renan Benvenuti",
      "Renan Migliorini",
      "Renata matos",
      "Renato Winnig",
      "Robson Zumkeller",
      "Robson Zumkeller",
      "RODRIGO ANTONIO QUEIROZ COSTA",
      "Rodrigo Peixoto",
      "Sandra Ribeiro Cameira",
      "Simbïo Design",
      "Studio Allure",
      "tellus",
      "Thayane",
      "Thiago Barreto",
      "Thiago Vieira Marques",
      "Thoz",
      "tiago taveira",
      "Tudo é Acessibilidade",
      "UERJ",
      "Vagner Trevisan",
      "Vanessa Silva",
      "Victor Maluhy",
      "Victor Mascarenhas",
      "VIRGINIA CORNELSEN",
      "Visorama",
      "Wagner Lúcio",
      "weme"
    ]
  },
  {
    country: "Bulgaria",
    supporters: ["Ivelina Dimitrova"]
  },
  {
    country: "Canada",
    supporters: [
      "À Hauteur d'homme",
      "Ardeshir Amini",
      "Cense Ltd.",
      "Elane Bowden",
      "Fletcher Scott Studio Inc.",
      "Meghan Hellstern",
      "PITCH PR",
      "PITCH PR",
      "Project 42",
      "Ryan Mayer",
      "SUPERFORT Creative Agency"
    ]
  },
  {
    country: "China",
    supporters: [
      "Campaign Design",
      "Orange Creatives",
      "Platform88"
    ]
  },
  {
    country: "Colombia",
    supporters: [
      "Adelaida Gonzalez",
      "Andrea Gonzalez OSCAR"
    ]
  },
  {
    country: "Croatia",
    supporters: ["Entain"]
  },
  {
    country: "Guatemala",
    supporters: ["Fabrizio Constanza"]
  },
  {
    country: "India",
    supporters: [
      "A BLUNT STORY",
      "Aboa Hasa Foundation",
      "Dinu Prasanna Kennedy",
      "DxE Inc.",
      "LOCAL",
      "Minto Joy",
      "Sai Challa",
      "Shona Sinha",
      "Shreya Salian"
    ]
  }
];

export const categories = ["All", "Events", "Case Studies", "Updates", "Perspective"];
export const chapters = ["All", "D! UK", "D! Ireland", "D! Australia"];

export const posts = [
  {
    type: "Case Studies",
    chapter: "D! Ireland",
    date: "30.04.2025, 04 PM:30",
    title: "Embedding Sustainability in the Design Curriculum",
    excerpt:
      "Outlining the journey of how the Design Declares initiative was integrated into the National College of Art and Design's curriculum for BA Graphic Design students.",
    image: "latest-category1.webp",
  },
  {
    type: "Events",
    chapter: "D! UK",
    date: "24.04.2025, 03 PM:30",
    title:
      "SD4P Collective: How can Service Design drive meaningful sustainability impact",
    excerpt: "Recap: SD4P Collective working session – 28th March 2025",
    image: "latest-category2.jpg",
  },
  {
    type: "Perspective",
    chapter: "D! Australia",
    date: "18.12.2024, 08 AM:38",
    title: "Sasha Titchkosky Interview",
    excerpt:
      "An Interview with Koskela Founder and Design Declares Australia Board Member - Sasha Titchkosky",
    image: "latest-category3.jpg",
  },
  {
    type: "Perspective",
    chapter: "D! Australia",
    date: "10.12.2024, 08 AM:37",
    title: "Andrew Simpson Interview",
    excerpt:
      "An Interview with Vert Design and Design Declares Australia CEO - Andew Simpson",
    image: "latest-category1.webp",
  },
  {
    type: "Events",
    chapter: "D! UK",
    date: "06.12.2024, 02 PM:30",
    title: "Designing Tomorrow: Speculative Thinking Shapes Our Present",
    excerpt:
      "Design Declares' November Event Challenges Perspectives on Sustainability and Innovation",
    image: "latest-category2.jpg",
  },
  {
    type: "Events",
    chapter: "D! Ireland",
    date: "27.06.2024, 04 PM:30",
    title: "D! June Event Recap",
    excerpt:
      "Design Declares has always been about people. From the moment that Design Council CDO Cat Drew introduced Alexie Sommer and Jo Barnard back in 2022, followed by Abb-d Taiyo and Aurelie Lionet coming onboard and aligning to the vision, we knew Design Declares was something special.",
    image: "latest-category4.jpg",
  },
  {
    type: "Case Studies",
    chapter: "D! UK",
    date: "26.06.2024, 02 PM:30",
    title: "Reducing Website Carbon Emissions",
    excerpt:
      "In an industry first, MEK have documented exactly how they approached and solved this challenge so they can inspire others to do the same and help businesses transition to sustainable digital practices.",
    image: "latest-category1.webp",
  },
  {
    type: "Updates",
    chapter: "D! UK",
    date: "01.06.2023, 04 PM:30",
    title: "What's the future for Design Declares?",
    excerpt:
      "A few months ago, an article by Chris Hockell was published in Dezeen criticising Architects Declare for failing to live up to its ambitions.",
    image: "latest-category4.jpg",
  },
];